export interface DictionaryEntry {
  id: string;
  originalToken: string;
  category: 'customer' | 'location' | 'service' | 'device' | 'other';
  shortName: string;
  longName: string;
  koreanName: string;
  aliases: string[];
  autoGenerated: boolean;
  userEdited: boolean;
}

export interface NameDictionary {
  version: number;
  createdAt: string;
  updatedAt: string;
  configFingerprint: string;
  entries: DictionaryEntry[];
}

export interface DescriptionSource {
  text: string;
  sourceType: 'port' | 'service' | 'sap' | 'interface';
  hostname: string;
  serviceId?: number;
  serviceType?: string;
}

/** AI 전송용 압축 형태 (토큰 절약) */
export interface DictionaryCompact {
  entries: {
    /** originalToken */
    t: string;
    /** shortName */
    s: string;
    /** longName */
    l: string;
    /** koreanName */
    k: string;
    /** aliases */
    a: string[];
  }[];
}
