/** v4.4.0: 3-field structure (name, configKeywords, searchAliases) */
export interface DictionaryEntry {
  id: string;
  name: string;                  // 그룹 대표 이름 (예: "SK쉴더스")
  configKeywords: string[];      // Config description에서 검색할 키워드들
  searchAliases: string[];       // 추가 사용자 검색어들
  autoGenerated: boolean;
  userEdited: boolean;
}

export interface NameDictionary {
  version: number;
  createdAt: string;
  updatedAt: string;
  entries: DictionaryEntry[];
}

export interface DescriptionSource {
  text: string;
  sourceType: 'port' | 'service' | 'sap' | 'interface';
  hostname: string;
  serviceId?: number;
  serviceType?: string;
}

/** AI 전송용 압축 형태 (토큰 절약) - v4.4.0 */
export interface DictionaryCompact {
  entries: {
    /** name (group representative name) */
    n: string;
    /** configKeywords (Config search targets) */
    k: string[];
    /** searchAliases (user search terms) */
    a: string[];
  }[];
}
